In [1]:
import pandas as pd
import numpy as np

repairs_df = pd.read_csv(
    "training_repairs_v3.csv"
)

print(repairs_df.shape)

repairs_df.head()

(500, 31)

,age_op,age_th,edu_op,edu_th,hours_op,hours_th,gain_val,original_spd,selected_rows,selectivity,...,repair_edu_th,repair_hours_op,repair_hours_th,repair_gain_val,repair_spd,distance,delta_age,delta_edu,delta_hours,delta_gain
0,>=,31,>=,9,>=,51,0,0.268526,2291,0.070360,...,9,>=,51,1,0.198188,1.000000,0,0,0,1
1,>=,48,>=,6,>=,39,0,0.301544,4888,0.150118,...,6,>=,41,1,0.112121,1.051282,0,0,2,1
2,<=,57,>=,9,>=,36,1,0.237864,1919,0.058936,...,9,>=,41,1,0.172747,0.138889,0,0,5,0
3,>=,44,>=,11,>=,55,0,0.343355,456,0.014004,...,11,>=,55,1,0.174359,1.000000,0,0,0,1
4,>=,36,<=,15,>=,56,1,0.246103,235,0.007217,...,16,>=,57,1,0.188054,0.084524,0,1,1,0

In [2]:
print(
    repairs_df.columns.tolist()
)

['age_op', 'age_th', 'edu_op', 'edu_th', 'hours_op', 'hours_th', 'gain_val', 'original_spd', 'selected_rows', 'selectivity', 'male_ratio', 'female_ratio', 'positive_rate', 'male_positive_rate', 'female_positive_rate', 'age_percentile', 'edu_percentile', 'hours_percentile', 'repair_age_op', 'repair_age_th', 'repair_edu_op', 'repair_edu_th', 'repair_hours_op', 'repair_hours_th', 'repair_gain_val', 'repair_spd', 'distance', 'delta_age', 'delta_edu', 'delta_hours', 'delta_gain']

In [3]:
repairs_df.shape

(500, 31)

In [4]:
repairs_df.columns.tolist()

['age_op',
 'age_th',
 'edu_op',
 'edu_th',
 'hours_op',
 'hours_th',
 'gain_val',
 'original_spd',
 'selected_rows',
 'selectivity',
 'male_ratio',
 'female_ratio',
 'positive_rate',
 'male_positive_rate',
 'female_positive_rate',
 'age_percentile',
 'edu_percentile',
 'hours_percentile',
 'repair_age_op',
 'repair_age_th',
 'repair_edu_op',
 'repair_edu_th',
 'repair_hours_op',
 'repair_hours_th',
 'repair_gain_val',
 'repair_spd',
 'distance',
 'delta_age',
 'delta_edu',
 'delta_hours',
 'delta_gain']

In [5]:
from sklearn.model_selection import train_test_split

X = repairs_df.drop(
    columns=[
        "delta_age",
        "delta_edu",
        "delta_hours",
        "delta_gain"
    ]
)

y = repairs_df[
    [
        "delta_age",
        "delta_edu",
        "delta_hours",
        "delta_gain"
    ]
]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(400, 27)
(100, 27)

In [6]:
print(X.columns.tolist())

['age_op', 'age_th', 'edu_op', 'edu_th', 'hours_op', 'hours_th', 'gain_val', 'original_spd', 'selected_rows', 'selectivity', 'male_ratio', 'female_ratio', 'positive_rate', 'male_positive_rate', 'female_positive_rate', 'age_percentile', 'edu_percentile', 'hours_percentile', 'repair_age_op', 'repair_age_th', 'repair_edu_op', 'repair_edu_th', 'repair_hours_op', 'repair_hours_th', 'repair_gain_val', 'repair_spd', 'distance']

In [7]:
print(repairs_df["age_op"].unique())
print(repairs_df["edu_op"].unique())
print(repairs_df["hours_op"].unique())

print()

print(repairs_df["repair_age_op"].unique())
print(repairs_df["repair_edu_op"].unique())
print(repairs_df["repair_hours_op"].unique())

['>=' '<=']
['>=' '<=']
['>=' '<=']

['>=' '<=']
['>=' '<=']
['>=' '<=']

In [8]:
repairs_encoded = repairs_df.copy()

op_map = {
    ">=": 1,
    "<=": 0
}

for col in [
    "age_op",
    "edu_op",
    "hours_op",
    "repair_age_op",
    "repair_edu_op",
    "repair_hours_op"
]:
    repairs_encoded[col] = repairs_encoded[col].map(op_map)

print(
    repairs_encoded[
        [
            "age_op",
            "edu_op",
            "hours_op"
        ]
    ].head()
)

   age_op  edu_op  hours_op
0       1       1         1
1       1       1         1
2       0       1         1
3       1       1         1
4       1       0         1

In [9]:
from sklearn.model_selection import train_test_split

X = repairs_encoded.drop(
    columns=[
        "delta_age",
        "delta_edu",
        "delta_hours",
        "delta_gain"
    ]
)

y = repairs_encoded[
    [
        "delta_age",
        "delta_edu",
        "delta_hours",
        "delta_gain"
    ]
]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(400, 27)
(100, 27)

In [10]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

model.fit(
    X_train,
    y_train
)

print("Training Complete")

Training Complete

In [11]:
# Generating Predictions
preds = model.predict(X_test)

preds_df = pd.DataFrame(
    preds,
    columns=[
        "delta_age",
        "delta_edu",
        "delta_hours",
        "delta_gain"
    ]
)

preds_df.head()

   delta_age  delta_edu  delta_hours  delta_gain
0     -0.475     -0.645       -0.025       0.900
1     -0.260      0.980       -0.225       0.045
2      0.610     -0.070       -0.575      -0.015
3     -0.935     -0.070       -0.320       0.030
4     -0.610      0.055       -0.865       0.010

In [12]:
# Computing Prediction Error
errors = abs(
    y_test.reset_index(drop=True)
    -
    preds_df
)

errors.head()

   delta_age  delta_edu  delta_hours  delta_gain
0      0.475      0.355        0.025       0.100
1      0.260      1.020        0.225       0.045
2      0.610      0.070        2.575       0.015
3      1.935      0.070        3.320       0.030
4      0.390      0.055        0.865       0.010

In [13]:
# Difficulty Score
errors["difficulty"] = (
    errors["delta_age"]
    +
    errors["delta_edu"]
    +
    errors["delta_hours"]
    +
    errors["delta_gain"]
)

errors["difficulty"].describe()

count    100.000000
mean       1.787800
std        1.215925
min        0.120000
25%        0.856250
50%        1.467500
75%        2.612500
max        5.355000
Name: difficulty, dtype: float64

In [14]:
errors["difficulty"].describe()

count    100.000000
mean       1.787800
std        1.215925
min        0.120000
25%        0.856250
50%        1.467500
75%        2.612500
max        5.355000
Name: difficulty, dtype: float64

In [15]:
# Identifying Hard Queries
threshold = errors["difficulty"].quantile(0.75)

print("Difficulty Threshold =", threshold)

errors["hard_query"] = (
    errors["difficulty"] >= threshold
)

print()

print(
    errors["hard_query"].value_counts()
)

Difficulty Threshold = 2.6125

hard_query
False    75
True     25
Name: count, dtype: int64

In [16]:
from sklearn.ensemble import RandomForestClassifier

difficulty_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

difficulty_model.fit(
    X_test,
    errors["hard_query"]
)

print("Difficulty model trained")

Difficulty model trained

In [17]:
pred_hard = difficulty_model.predict(
    X_test
)

from sklearn.metrics import accuracy_score

print(
    "Accuracy =",
    accuracy_score(
        errors["hard_query"],
        pred_hard
    )
)

Accuracy = 1.0

In [18]:
def run_query_v2(data, q):

    result = data.copy()

    if q["age_op"] == ">=":
        result = result[result["age"] >= q["age_th"]]
    else:
        result = result[result["age"] <= q["age_th"]]

    if q["edu_op"] == ">=":
        result = result[result["education_num"] >= q["edu_th"]]
    else:
        result = result[result["education_num"] <= q["edu_th"]]

    if q["hours_op"] == ">=":
        result = result[result["hours_per_week"] >= q["hours_th"]]
    else:
        result = result[result["hours_per_week"] <= q["hours_th"]]

    result = result[
        result["capital_gain_binary"] == q["gain_val"]
    ]

    return result

In [19]:
# Implementing SPD Calculation
def compute_spd(data):
    male = data[data["sex"] == "Male"]
    female = data[data["sex"] == "Female"]

    if len(male) == 0 or len(female) == 0:
        return None

    p_male = male["income"].mean()
    p_female = female["income"].mean()

    spd = p_male - p_female

    return spd

In [20]:
def build_ml_repair(
    query,
    prediction
):

    repair = {}

    repair["age_op"] = decode_operator(
    query["age_op"]
    )

    repair["edu_op"] = decode_operator(
    query["edu_op"]
    )

    repair["hours_op"] = decode_operator(
    query["hours_op"]
    )

    repair["age_th"] = int(
        query["age_th"]
        + prediction["delta_age"]
    )

    repair["edu_th"] = int(
        query["edu_th"]
        + prediction["delta_edu"]
    )

    repair["hours_th"] = int(
        query["hours_th"]
        + prediction["delta_hours"]
    )

    repair["gain_val"] = int(
        query["gain_val"]
        + prediction["delta_gain"]
    )

    repair["gain_val"] = max(
        0,
        min(1, repair["gain_val"])
    )

    return repair

In [21]:
def decode_operator(op):

    if op == 1:
        return ">="

    return "<="

In [22]:
sample_query = X_test.iloc[0]

sample_pred = preds_df.iloc[0]

ml_repair = build_ml_repair(
    sample_query,
    sample_pred
)

print(ml_repair)

{'age_op': '>=', 'edu_op': '>=', 'hours_op': '<=', 'age_th': 32, 'edu_th': 14, 'hours_th': 42, 'gain_val': 0}

In [23]:
from itertools import product

def generate_neighbors(
    ml_repair,
    radius=1
):

    age_vals = range(
        ml_repair["age_th"] - radius,
        ml_repair["age_th"] + radius + 1
    )

    edu_vals = range(
        ml_repair["edu_th"] - radius,
        ml_repair["edu_th"] + radius + 1
    )

    hours_vals = range(
        ml_repair["hours_th"] - radius,
        ml_repair["hours_th"] + radius + 1
    )

    gain_vals = [0, 1]

    neighbors = []

    for age, edu, hours, gain in product(
        age_vals,
        edu_vals,
        hours_vals,
        gain_vals
    ):

        candidate = ml_repair.copy()

        candidate["age_th"] = age
        candidate["edu_th"] = edu
        candidate["hours_th"] = hours
        candidate["gain_val"] = gain

        neighbors.append(candidate)

    return neighbors

In [24]:
neighbors = generate_neighbors(
    ml_repair,
    radius=1
)

print(
    "Number of neighbors:",
    len(neighbors)
)

neighbors[:3]

Number of neighbors: 54

[{'age_op': '>=',
  'edu_op': '>=',
  'hours_op': '<=',
  'age_th': 31,
  'edu_th': 13,
  'hours_th': 41,
  'gain_val': 0},
 {'age_op': '>=',
  'edu_op': '>=',
  'hours_op': '<=',
  'age_th': 31,
  'edu_th': 13,
  'hours_th': 41,
  'gain_val': 1},
 {'age_op': '>=',
  'edu_op': '>=',
  'hours_op': '<=',
  'age_th': 31,
  'edu_th': 13,
  'hours_th': 42,
  'gain_val': 0}]

In [25]:
# Fairness Evaluator For Neighbors
def find_best_neighbor(
    neighbors,
    df
):

    fair_neighbors = []

    for candidate in neighbors:

        result = run_query_v2(
            df,
            candidate
        )

        if len(result) < 100:
            continue

        spd = compute_spd(result)

        if spd is None:
            continue

        if abs(spd) <= 0.20:

            fair_neighbors.append(
                (
                    candidate,
                    abs(spd),
                    len(result)
                )
            )

    return fair_neighbors

In [26]:
import pandas as pd

adult_columns = [
    "age",
    "workclass",
    "fnlwgt",
    "education",
    "education_num",
    "marital_status",
    "occupation",
    "relationship",
    "race",
    "sex",
    "capital_gain",
    "capital_loss",
    "hours_per_week",
    "native_country",
    "income"
]

df = pd.read_csv(
    "adult.data",
    header=None,
    names=adult_columns,
    skipinitialspace=True
)

print(df.shape)
df.head()

(32561, 15)

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [27]:
print(df.shape)

(32561, 15)

In [28]:
df["capital_gain_binary"] = (
    df["capital_gain"] > 0
).astype(int)

print(
    df["capital_gain_binary"]
    .value_counts()
)

capital_gain_binary
0    29849
1     2712
Name: count, dtype: int64

In [29]:
print(
    "capital_gain_binary"
    in df.columns
)

True

In [30]:
df["income"] = (
    df["income"]
    .str.strip()
    .map({
        "<=50K": 0,
        ">50K": 1
    })
)

print(
    df["income"]
    .value_counts()
)

income
0    24720
1     7841
Name: count, dtype: int64

In [31]:
print(
    df["income"].dtype
)

int64

In [32]:
fair_neighbors = find_best_neighbor(
    neighbors,
    df
)

print(
    "Fair neighbors:",
    len(fair_neighbors)
)

Fair neighbors: 18

In [33]:
print(len(preds_df))
print(len(X_test))

100
100

In [34]:
guided_success = 0

guided_fail = 0

total_queries = len(X_test)

print(total_queries)

100

In [35]:
for i in range(len(X_test)):

    query = X_test.iloc[i]

    prediction = preds_df.iloc[i]

    ml_repair = build_ml_repair(
        query,
        prediction
    )

    neighbors = generate_neighbors(
        ml_repair,
        radius=1
    )

    fair_neighbors = find_best_neighbor(
        neighbors,
        df
    )

    if len(fair_neighbors) > 0:

        guided_success += 1

    else:

        guided_fail += 1

In [36]:
print("Total Queries:", total_queries)

print("Guided Success:", guided_success)

print("Guided Fail:", guided_fail)

print()

print(
    "Guided Success Rate:",
    round(
        100 * guided_success / total_queries,
        2
    ),
    "%"
)

Total Queries: 100
Guided Success: 87
Guided Fail: 13

Guided Success Rate: 87.0 %

In [37]:
test_query = X_test.iloc[0]

prediction = preds_df.iloc[0]

repair = build_ml_repair(
    test_query,
    prediction
)

neighbors = generate_neighbors(
    repair,
    radius=1
)

print(len(neighbors))

54

In [40]:
print(globals().keys())

dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__builtin__', '__builtins__', '_ih', '_oh', '_dh', 'In', 'Out', 'get_ipython', 'exit', 'quit', '_', '__', '___', '_i', '_ii', '_iii', '_i1', 'pd', 'np', 'repairs_df', '_1', '_i2', '_i3', '_3', '_i4', '_4', '_i5', 'train_test_split', 'X', 'y', 'X_train', 'X_test', 'y_train', 'y_test', '_i6', '_i7', '_i8', 'repairs_encoded', 'op_map', 'col', '_i9', '_i10', 'RandomForestRegressor', 'model', '_i11', 'preds', 'preds_df', '_11', '_i12', 'errors', '_12', '_i13', '_13', '_i14', '_14', '_i15', 'threshold', '_i16', 'RandomForestClassifier', 'difficulty_model', '_i17', 'pred_hard', 'accuracy_score', '_i18', 'run_query_v2', '_i19', 'compute_spd', '_i20', 'build_ml_repair', '_i21', 'decode_operator', '_i22', 'sample_query', 'sample_pred', 'ml_repair', '_i23', 'product', 'generate_neighbors', '_i24', 'neighbors', '_24', '_i25', 'find_best_neighbor', '_i26', 'adult_columns', 'df', '_26', '_i27', '_i28', '_i29', '_i30', '_i31', '_i32', 'fair_neighbors', '_i33', '_i34', 'guided_success', 'guided_fail', 'total_queries', '_i35', 'i', 'query', 'prediction', '_i36', '_i37', 'test_query', 'repair', '_i38', '_i39', 'name', '_i40'])